"""final migration

Revision ID: fdc494ab7685
Revises: ab8cf4dcb6da
Create Date: 2023-08-03 17:44:40.623056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc494ab7685'
down_revision = 'ab8cf4dcb6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
